name: Build Android

on:
  push:
    branches:
      - libryujinx_bionic

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up JDK 17
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      # Step 3: Download and set up .NET SDK 9.0
      - name: Download .NET SDK 9.0
        run: |
          wget https://dot.net/v1/dotnet-install.sh
          chmod +x dotnet-install.sh
          ./dotnet-install.sh --version 9.0.100-preview.6.24328.19 --install-dir $HOME/dotnet
          echo "$HOME/dotnet" >> $GITHUB_PATH

      # Step 4: Restore .NET dependencies
      - name: Restore .NET Dependencies
        run: dotnet restore

      # Step 5: Configure Android Build
      - name: Configure Android Build
        run: |
          echo "org.ryujinx.llvm.toolchain.path=${ANDROID_HOME}/ndk/25.1.8937393/toolchains/llvm/prebuilt/linux-x86_64/bin" >> src/RyujinxAndroid/gradle.properties

      # Step 6: Build the Android project
      - name: Build the Android project
        run: |
          cd src/RyujinxAndroid
          chmod +x gradlew
          ./gradlew --stacktrace assembleDebug

      # Step 7: Upload APK artifact
      - name: Upload APK Artifact
        uses: actions/upload-artifact@v3
        with:
          name: app-debug.apk
          path: src/RyujinxAndroid/app/build/outputs/apk/debug/app-debug.apk
